<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <ItemGroup>
    <ProjectReference Include="..\AutomationLauncher.App.Core\AutomationLauncher.App.Core.csproj" />
    <ProjectReference Include="..\AutomationLauncher.Domain\AutomationLauncher.Domain.csproj" />
    <ProjectReference Include="..\AutomationLauncher.Application\AutomationLauncher.Application.csproj" />
    <ProjectReference Include="..\AutomationLauncher.Infrastructure\AutomationLauncher.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.Extensions.Hosting" />
    <PackageReference Include="Serilog.Settings.Configuration" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="Serilog.Sinks.File" />
    <PackageReference Include="System.Text.Json" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.DirectoryServices.AccountManagement" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyVersion>10.0.0.0</AssemblyVersion>
    <FileVersion>10.0.0.0</FileVersion>
    <Version>10.0.0</Version>
    <InformationalVersion>10.0.0</InformationalVersion>
  </PropertyGroup>
</Project>
